name: model_train
permissions:
  id-token: write
  contents: write


on:
  - push

jobs:
  run:
   runs-on:
     - ubuntu-latest
   steps:
     - uses: iterative/setup-cml@v1
     - uses: actions/checkout@v3
     - name: train model
     

       run: |
          pip install -r requirements.txt
          python train_model.py

          echo "RF and LR model score" > report.md
          cat report.txt

          echo "Confusion Matrix and Feature Importance" > report1.md

          cat report.md report1.md > combined.md

          cml comment create combined.md



          
